name: barcode_reader

description: قارئ باركود وQR احترافي مع سجل محلي.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^3.5.7
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4

flutter:
  uses-material-design: true
